[workspace]
resolver = "3"
members = [
  "crates/api",
  "crates/http-cache",
  "crates/middleware",
  "crates/platform",
  "crates/postgres",
  "crates/worker",
]

[workspace.dependencies]
alternate-http-cache.path = "crates/http-cache"
alternate-middleware.path = "crates/middleware"
alternate-platform.path = "crates/platform"

alternate-authentication = { version = "0.1.0", registry = "self-hosted", git = "https://git.thealternate.dev/alternate/foundation", rev = "54bcbbac0d52f0baacf0318d3d0d68432c265d31" }
alternate-codec = { version = "0.1.0", registry = "self-hosted", git = "https://git.thealternate.dev/alternate/foundation", rev = "54bcbbac0d52f0baacf0318d3d0d68432c265d31" }
alternate-crypto = { version = "0.1.0", registry = "self-hosted", git = "https://git.thealternate.dev/alternate/foundation", rev = "54bcbbac0d52f0baacf0318d3d0d68432c265d31" }
alternate-domain = { version = "0.1.0", registry = "self-hosted", git = "https://git.thealternate.dev/alternate/foundation", rev = "54bcbbac0d52f0baacf0318d3d0d68432c265d31" }

alternate-http = { version = "0.1.0", registry = "self-hosted", git = "https://git.thealternate.dev/alternate/platform", rev = "ba05eeffec2877bc864553179772d48c3eaa3a07" }
alternate-kv = { version = "0.1.0", registry = "self-hosted", git = "https://git.thealternate.dev/alternate/platform", rev = "ba05eeffec2877bc864553179772d48c3eaa3a07" }
alternate-migration = { version = "0.1.0", registry = "self-hosted", git = "https://git.thealternate.dev/alternate/platform", rev = "ba05eeffec2877bc864553179772d48c3eaa3a07" }
alternate-queue = { version = "0.1.0", registry = "self-hosted", git = "https://git.thealternate.dev/alternate/platform", rev = "ba05eeffec2877bc864553179772d48c3eaa3a07" }

anyhow = "1.0.104"
jiff = "0.2.35"
serde.version = "1.0.229"
thiserror = "2.0.20"
tracing = "0.1.44"
uuid = "1.26.1"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
missing_errors_doc = "allow"
must_use_candidate = "allow"
unused_async_trait_impl = "allow"
