[package]
name = "alternate-api"
version = "0.1.0"
edition = "2024"

[dependencies]
alternate-authentication.workspace = true
alternate-crypto = { workspace = true, features = ["base64"] }
alternate-domain.workspace = true
alternate-middleware.workspace = true

anyhow.workspace = true
axum = { version = "0.8.9", features = ["macros"] }
axum-extra = { version = "0.12.6", features = ["cookie", "query"] }
serde.workspace = true
serde_json = "1.0.151"
time.version = "0.3.55"
utoipa = { version = "5.5.0", features = ["uuid"] }
uuid = { workspace = true, features = ["serde"] }

[dev-dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt"] }

[lints]
workspace = true
